name: "Scheduled Runners"

on:
    schedule:
        - cron: '*/2 * * * *'

jobs:
    run-schedule:
        runs-on: ubuntu-latest
        steps:
            - name: "Output Server Time"
              run: echo " This is current server time is $(date)"